export const producttabledata = [
    {
        id: 1,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 2,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 3,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 4,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 5,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 6,
        product_name: "Product Name 6",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 7,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 8,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 9,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 10,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 11,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 12,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 13,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 14,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 15,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 16,
        product_name: "",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 17,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 18,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 19,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 20,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 21,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 22,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 23,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 24,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 25,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 26,
        product_name: "",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 27,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 28,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 29,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 30,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
];

export const statusData = [
    { value: "", label: "All" },
    { value: "Pending", label: "Pending" },
    { value: "Accredited", label: "Accredited" },
    { value: "Rejected", label: "Rejected" },
];
export const AccreditationData = [
    { value: "", label: "All" },
    { value: "Vegetarian", label: "Vegetarian" },
    { value: "Plant-Based", label: "Plant" },
    { value: "Vegan", label: "Vegan" },
];

export const productNotes = {
    data: [
        {
            created_at: "12:32pm 23/12/2024",
            added_by: "User Notes",
            note: "We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle.",
        },
        {
            created_at: "11:32pm 23/12/2024",
            added_by: "Admin Notes",
            note: "Whether veggie, vegan or flexi, our support and advice empowers members and the general public on their journey towards a better life for all. We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle.",
        },
        {
            created_at: "10:32pm 23/12/2024",
            added_by: "Admin Notes",
            note: "We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle. Whether veggie, vegan or flexi, our support and advice empowers members and the general public on their journey towards a better life for all.",
        },
    ],
};

export const IngredientData = [] ;