export const producttabledata = [
    {
        id: 1,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 2,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 3,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 4,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 5,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 6,
        product_name: "Product Name 6",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 7,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 8,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 9,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 10,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 11,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 12,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 13,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 14,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 15,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 16,
        product_name: "",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 17,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 18,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 19,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 20,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 21,
        product_name: "Product Name 1",
        requested_accreditation: "Vegetarian",
        submitted_on: "23/10/2024",
        response_date: "N/A",
        accreditation_status: "Pending",
    },
    {
        id: 22,
        product_name: "Product Name 2",
        requested_accreditation: "Vegetarian",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 23,
        product_name: "Product Name 3",
        requested_accreditation: "Vegan",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 24,
        product_name: "Product Name 4",
        requested_accreditation: "Plant-Based",
        submitted_on: "25/10/2024",
        response_date: "26/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 25,
        product_name: "Product Name 5",
        requested_accreditation: "Vegan",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 26,
        product_name: "",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 27,
        product_name: "Product Name 7",
        requested_accreditation: "Vegetarian",
        submitted_on: "27/10/2024",
        response_date: "28/10/2024",
        accreditation_status: "Accredited",
    },
    {
        id: 28,
        product_name: "Product Name 8",
        requested_accreditation: "Vegetarian",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 29,
        product_name: "Product Name 9",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "29/10/2024",
        accreditation_status: "Rejected",
    },
    {
        id: 30,
        product_name: "Product Name 10",
        requested_accreditation: "Vegan",
        submitted_on: "29/10/2024",
        response_date: "30/10/2024",
        accreditation_status: "Accredited",
    },
];

export const statusData = [
    { value: "", label: "All" },
    { value: "Pending", label: "Pending" },
    { value: "Accredited", label: "Accredited" },
    { value: "Rejected", label: "Rejected" },
];
export const AccreditationData = [
    { value: "", label: "All" },
    { value: "Vegetarian", label: "Vegetarian" },
    { value: "Plant-Based", label: "Plant" },
    { value: "Vegan", label: "Vegan" },
];

export const productNotes = {
    data: [
        {
            created_at: "12:32pm 23/12/2024",
            added_by: "User Notes",
            note: "We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle.",
        },
        {
            created_at: "11:32pm 23/12/2024",
            added_by: "Admin Notes",
            note: "Whether veggie, vegan or flexi, our support and advice empowers members and the general public on their journey towards a better life for all. We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle.",
        },
        {
            created_at: "10:32pm 23/12/2024",
            added_by: "Admin Notes",
            note: "We are the rallying cry for the vegetarian movement, championing the cause and inspiring everyone to move towards a vegetarian or vegan lifestyle. Whether veggie, vegan or flexi, our support and advice empowers members and the general public on their journey towards a better life for all.",
        },
    ],
};

export const IngredientData = [
    {
        id: 1,
        ingredient_name: "Ingredient Name 1",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 2,
        plant_based: 1,
        date_added: "23/10/2024",
    },
    {
        id: 2,
        ingredient_name: "Ingredient Name 2",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 1,
        date_added: "25/10/2024",
    },
    {
        id: 3,
        ingredient_name: "Ingredient Name 3",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 1,
        date_added: "25/10/2024",
    },
    {
        id: 4,
        ingredient_name: "Ingredient Name 4",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 1,
        date_added: "25/10/2024",
    },
    {
        id: 5,
        ingredient_name: "Ingredient Name 5",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 2,
        date_added: "27/10/2024",
    },
    {
        id: 6,
        ingredient_name: "Ingredient Name 6",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 1,
        plant_based: 0,
        date_added: "27/10/2024",
    },
    {
        id: 7,
        ingredient_name: "Ingredient Name 7",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 0,
        date_added: "27/10/2024",
    },
    {
        id: 8,
        ingredient_name: "Ingredient Name 8",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 0,
        date_added: "29/10/2024",
    },
    {
        id: 9,
        ingredient_name: "Ingredient Name 9",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 1,
        date_added: "29/10/2024",
    },
    {
        id: 10,
        ingredient_name: "Ingredient Name 10",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 1,
        plant_based: 2,
        date_added: "29/10/2024",
    },
    {
        id: 11,
        ingredient_name: "Ingredient Name 11",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 2,
        plant_based: 2,
        date_added: "30/10/2024",
    },
    {
        id: 12,
        ingredient_name: "Ingredient Name 12",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 0,
        date_added: "30/10/2024",
    },
    {
        id: 13,
        ingredient_name: "Ingredient Name 13",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 1,
        date_added: "31/10/2024",
    },
    {
        id: 14,
        ingredient_name: "Ingredient Name 14",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 2,
        plant_based: 1,
        date_added: "31/10/2024",
    },
    {
        id: 15,
        ingredient_name: "Ingredient Name 15",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 2,
        date_added: "01/11/2024",
    },
    {
        id: 16,
        ingredient_name: "Ingredient Name 16",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 2,
        plant_based: 1,
        date_added: "02/11/2024",
    },
    {
        id: 17,
        ingredient_name: "Ingredient Name 17",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 1,
        date_added: "02/11/2024",
    },
    {
        id: 18,
        ingredient_name: "Ingredient Name 18",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 0,
        date_added: "03/11/2024",
    },
    {
        id: 19,
        ingredient_name: "Ingredient Name 19",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 1,
        plant_based: 2,
        date_added: "04/11/2024",
    },
    {
        id: 20,
        ingredient_name: "Ingredient Name 20",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 1,
        date_added: "05/11/2024",
    },
    {
        id: 21,
        ingredient_name: "Ingredient Name 21",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 2,
        date_added: "06/11/2024",
    },
    {
        id: 22,
        ingredient_name: "Ingredient Name 22",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 1,
        date_added: "07/11/2024",
    },
    {
        id: 23,
        ingredient_name: "Ingredient Name 23",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 0,
        date_added: "08/11/2024",
    },
    {
        id: 24,
        ingredient_name: "Ingredient Name 13",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 1,
        date_added: "31/10/2024",
    },
    {
        id: 25,
        ingredient_name: "Ingredient Name 14",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 2,
        plant_based: 1,
        date_added: "31/10/2024",
    },
    {
        id: 26,
        ingredient_name: "Ingredient Name 15",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 1,
        plant_based: 2,
        date_added: "01/11/2024",
    },
    {
        id: 27,
        ingredient_name: "Ingredient Name 16",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 2,
        plant_based: 1,
        date_added: "02/11/2024",
    },
    {
        id: 28,
        ingredient_name: "Ingredient Name 17",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 2,
        vegan: 2,
        plant_based: 1,
        date_added: "02/11/2024",
    },
    {
        id: 29,
        ingredient_name: "Ingredient Name 18",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 0,
        date_added: "03/11/2024",
    },
    {
        id: 30,
        ingredient_name: "Ingredient Name 19",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 0,
        vegan: 1,
        plant_based: 2,
        date_added: "04/11/2024",
    },
    {
        id: 31,
        ingredient_name: "Ingredient Name 20",
        alternate_names: [
            {
                id: 182,
                ingredient_id: 12,
                alternate_name: "Dahi",
            },
            {
                id: 183,
                ingredient_id: 12,
                alternate_name: "Curd",
            },
            {
                id: 184,
                ingredient_id: 12,
                alternate_name: "Chach",
            },
            {
                id: 185,
                ingredient_id: 12,
                alternate_name: "Lassi",
            },
            {
                id: 186,
                ingredient_id: 12,
                alternate_name: "Sour Buttermilk",
            },
            {
                id: 187,
                ingredient_id: 12,
                alternate_name: "Something",
            },
        ],
        vegetarian: 1,
        vegan: 0,
        plant_based: 1,
        date_added: "05/11/2024",
    },
];
