import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import ReduxProvider from "@/redux/provider";
import ToastProvider from "@/components/Toast/Toaster";
import Footer from "@/Module/Footer";
import NextTopLoader from 'nextjs-toploader';
import Loader from "@/components/Loader/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ReduxProvider>
        <NextTopLoader  showSpinner={false}/>
          <ToastProvider />
          <div className="">{children}</div> {/* Content */}
          <Loader />
        </ReduxProvider>
        {/* Footer */}
          <Footer />
      </body>
    </html>
  );
}
